const AUTH_ENDPOINT = "/auth";
const MAIL_ENDPOINT = "/email";
const USER_ENDPOINT = "/users";
const PRODUCT_ENDPOINT = "/products";

const GET_MERCHANT_FILTERS = PRODUCT_ENDPOINT+"/merchantfilters";
const GET_RARITY_FILTERS = PRODUCT_ENDPOINT+"/rarityfilters";

const REGISTER_EMAIL_ENDPOINT = MAIL_ENDPOINT+"/send";

const GET_USER_BY_EMAIL = USER_ENDPOINT+"/email";

const REGISTER_USER_ENDPOINT = AUTH_ENDPOINT+"/register";
const LOGIN_USER_ENDPOINT = AUTH_ENDPOINT+"/login";
const LOGIN_JWT_ENDPOINT = AUTH_ENDPOINT+"/self";
const LOGOUT_JWT_ENDPOINT = AUTH_ENDPOINT+"/logout";
const REFRESH_JWT_ENDPOINT = AUTH_ENDPOINT+"/refresh";

export {REGISTER_EMAIL_ENDPOINT, REGISTER_USER_ENDPOINT, LOGIN_USER_ENDPOINT, GET_USER_BY_EMAIL, REFRESH_JWT_ENDPOINT, LOGIN_JWT_ENDPOINT, LOGOUT_JWT_ENDPOINT, PRODUCT_ENDPOINT, GET_MERCHANT_FILTERS, GET_RARITY_FILTERS}