const AUTH_ENDPOINT = "/auth";
const MAIL_ENDPOINT = "/email";
const USER_ENDPOINT = "/users";

const REGISTER_EMAIL_ENDPOINT = MAIL_ENDPOINT+"/send";
const REGISTER_USER_ENDPOINT = AUTH_ENDPOINT+"/register";
const LOGIN_USER_ENDPOINT = AUTH_ENDPOINT+"/login";
const LOGIN_JWT_ENDPOINT = AUTH_ENDPOINT+"/self";
const GET_USER_BY_EMAIL = USER_ENDPOINT+"/email";
const REFRESH_JWT_ENDPOINT = AUTH_ENDPOINT+"/refresh";

export {REGISTER_EMAIL_ENDPOINT, REGISTER_USER_ENDPOINT, LOGIN_USER_ENDPOINT, GET_USER_BY_EMAIL, REFRESH_JWT_ENDPOINT, LOGIN_JWT_ENDPOINT}