const REGISTER_EMAIL_ENDPOINT = "/email/send";
const REGISTER_USER_ENDPOINT = "/auth/register";
const LOGIN_USER_ENDPOINT = "/auth/login";

export {REGISTER_EMAIL_ENDPOINT, REGISTER_USER_ENDPOINT, LOGIN_USER_ENDPOINT}