/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'unplugin-vue-router/types'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/Auth/Login/LoginPage': RouteRecordInfo<'/Auth/Login/LoginPage', '/Auth/Login/LoginPage', Record<never, never>, Record<never, never>>,
    '/Auth/Register/EmailRegisterPage': RouteRecordInfo<'/Auth/Register/EmailRegisterPage', '/Auth/Register/EmailRegisterPage', Record<never, never>, Record<never, never>>,
    '/Auth/Register/EmailSentPage': RouteRecordInfo<'/Auth/Register/EmailSentPage', '/Auth/Register/EmailSentPage', Record<never, never>, Record<never, never>>,
    '/Auth/Register/RegisterPage': RouteRecordInfo<'/Auth/Register/RegisterPage', '/Auth/Register/RegisterPage', Record<never, never>, Record<never, never>>,
    '/Auth/ResetPasswordPage': RouteRecordInfo<'/Auth/ResetPasswordPage', '/Auth/ResetPasswordPage', Record<never, never>, Record<never, never>>,
    '/Ecommerce/components/FormFilterComponent': RouteRecordInfo<'/Ecommerce/components/FormFilterComponent', '/Ecommerce/components/FormFilterComponent', Record<never, never>, Record<never, never>>,
    '/Ecommerce/EcommercePage': RouteRecordInfo<'/Ecommerce/EcommercePage', '/Ecommerce/EcommercePage', Record<never, never>, Record<never, never>>,
    '/Ecommerce/ProductDetailPage': RouteRecordInfo<'/Ecommerce/ProductDetailPage', '/Ecommerce/ProductDetailPage', Record<never, never>, Record<never, never>>,
    '/NotFoundPage': RouteRecordInfo<'/NotFoundPage', '/NotFoundPage', Record<never, never>, Record<never, never>>,
    '/Profile/ProfilePage': RouteRecordInfo<'/Profile/ProfilePage', '/Profile/ProfilePage', Record<never, never>, Record<never, never>>,
  }
}
